-- =====================================================================
-- Zovic — schema inicial
-- Fonte: docs/modelo-er.md
--
-- Convenções (ver "Implementação física" em docs/modelo-er.md):
--   * Nomes de constraints/índices seguem o padrão do Prisma
--     (<tabela>_pkey, <tabela>_<coluna>_fkey, <tabela>_<colunas>_key/_idx),
--     para que o schema.prisma não precise de `map:`.
--   * Tabelas com deleted_at usam soft delete.
--   * updated_at é mantido pelo trigger set_updated_at().
--   * Tabelas associativas têm PK composta e ON DELETE CASCADE.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Funções utilitárias
-- ---------------------------------------------------------------------

CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------
-- Tipos
-- ---------------------------------------------------------------------

-- Valores provisórios: o modelo ER não lista os eventos.
-- Para acrescentar: ALTER TYPE user_event_type ADD VALUE '...';
CREATE TYPE user_event_type AS ENUM (
    'sign_up',
    'login',
    'logout',
    'music_play',
    'music_skip'
);

-- =====================================================================
-- Planos e usuários
-- =====================================================================

CREATE TABLE plan_type (
    id          integer       GENERATED BY DEFAULT AS IDENTITY,
    name        varchar(100)  NOT NULL,
    price       numeric(10,2) NOT NULL,
    user_amount integer       NOT NULL,
    deleted_at  timestamptz,
    updated_at  timestamptz   NOT NULL DEFAULT now(),
    created_at  timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT plan_type_pkey PRIMARY KEY (id),
    CONSTRAINT plan_type_price_check CHECK (price >= 0),
    CONSTRAINT plan_type_user_amount_check CHECK (user_amount > 0)
);

CREATE TABLE plan (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(100) NOT NULL,
    type_id    integer      NOT NULL,
    deleted_at timestamptz,
    updated_at timestamptz  NOT NULL DEFAULT now(),
    created_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT plan_pkey PRIMARY KEY (id),
    CONSTRAINT plan_type_id_fkey FOREIGN KEY (type_id)
        REFERENCES plan_type (id) ON DELETE RESTRICT
);
CREATE INDEX plan_type_id_idx ON plan (type_id);

-- "user" é palavra reservada no Postgres: sempre entre aspas no SQL.
CREATE TABLE "user" (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(150) NOT NULL,
    birthdate  date,
    deleted_at timestamptz,
    updated_at timestamptz  NOT NULL DEFAULT now(),
    created_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE plan_user (
    plan_id  integer NOT NULL,
    user_id  integer NOT NULL,
    is_admin boolean NOT NULL DEFAULT false,
    CONSTRAINT plan_user_pkey PRIMARY KEY (plan_id, user_id),
    CONSTRAINT plan_user_plan_id_fkey FOREIGN KEY (plan_id)
        REFERENCES plan (id) ON DELETE CASCADE,
    CONSTRAINT plan_user_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE
);
CREATE INDEX plan_user_user_id_idx ON plan_user (user_id);

CREATE TABLE user_event (
    id         integer         GENERATED BY DEFAULT AS IDENTITY,
    user_id    integer         NOT NULL,
    event_type user_event_type NOT NULL,
    created_at timestamptz     NOT NULL DEFAULT now(),
    CONSTRAINT user_event_pkey PRIMARY KEY (id),
    CONSTRAINT user_event_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE
);
CREATE INDEX user_event_user_id_created_at_idx ON user_event (user_id, created_at);

-- Linha única. O modelo ER não prevê id; a coluna `singleton` existe só para
-- (1) impedir uma segunda linha e (2) dar ao Prisma o identificador que ele exige.
CREATE TABLE system_data (
    singleton  boolean     NOT NULL DEFAULT true,
    users      integer     NOT NULL DEFAULT 0,
    songs      integer     NOT NULL DEFAULT 0,
    playlists  integer     NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT system_data_pkey PRIMARY KEY (singleton),
    CONSTRAINT system_data_singleton_check CHECK (singleton),
    CONSTRAINT system_data_counts_check CHECK (users >= 0 AND songs >= 0 AND playlists >= 0)
);

-- =====================================================================
-- Catálogo musical
-- =====================================================================

CREATE TABLE musics (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255) NOT NULL,
    duration   integer      NOT NULL, -- segundos
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT musics_pkey PRIMARY KEY (id),
    CONSTRAINT musics_duration_check CHECK (duration > 0)
);

-- Ainda sem coluna de conteúdo: ver "Pontos em aberto" em docs/modelo-er.md.
CREATE TABLE lyrics (
    id         integer     GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT lyrics_pkey PRIMARY KEY (id)
);

CREATE TABLE lyrics_music (
    lyrics_id integer NOT NULL,
    music_id  integer NOT NULL,
    CONSTRAINT lyrics_music_pkey PRIMARY KEY (lyrics_id, music_id),
    CONSTRAINT lyrics_music_lyrics_id_fkey FOREIGN KEY (lyrics_id)
        REFERENCES lyrics (id) ON DELETE CASCADE,
    CONSTRAINT lyrics_music_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE
);
CREATE INDEX lyrics_music_music_id_idx ON lyrics_music (music_id);

CREATE TABLE genre (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(100) NOT NULL,
    color      char(7)      NOT NULL, -- hex: #RRGGBB
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT genre_pkey PRIMARY KEY (id),
    CONSTRAINT genre_color_check CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);
-- Nome único só entre os registros ativos (soft delete).
CREATE UNIQUE INDEX genre_name_key ON genre (name) WHERE deleted_at IS NULL;

CREATE TABLE genre_music (
    genre_id integer NOT NULL,
    music_id integer NOT NULL,
    CONSTRAINT genre_music_pkey PRIMARY KEY (genre_id, music_id),
    CONSTRAINT genre_music_genre_id_fkey FOREIGN KEY (genre_id)
        REFERENCES genre (id) ON DELETE CASCADE,
    CONSTRAINT genre_music_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE
);
CREATE INDEX genre_music_music_id_idx ON genre_music (music_id);

CREATE TABLE album (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT album_pkey PRIMARY KEY (id)
);

CREATE TABLE album_genre (
    genre_id integer NOT NULL,
    album_id integer NOT NULL,
    CONSTRAINT album_genre_pkey PRIMARY KEY (genre_id, album_id),
    CONSTRAINT album_genre_genre_id_fkey FOREIGN KEY (genre_id)
        REFERENCES genre (id) ON DELETE CASCADE,
    CONSTRAINT album_genre_album_id_fkey FOREIGN KEY (album_id)
        REFERENCES album (id) ON DELETE CASCADE
);
CREATE INDEX album_genre_album_id_idx ON album_genre (album_id);

CREATE TABLE album_music (
    album_id integer NOT NULL,
    music_id integer NOT NULL,
    CONSTRAINT album_music_pkey PRIMARY KEY (album_id, music_id),
    CONSTRAINT album_music_album_id_fkey FOREIGN KEY (album_id)
        REFERENCES album (id) ON DELETE CASCADE,
    CONSTRAINT album_music_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE
);
CREATE INDEX album_music_music_id_idx ON album_music (music_id);

CREATE TABLE artist (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT artist_pkey PRIMARY KEY (id)
);

CREATE TABLE album_artist (
    album_id  integer NOT NULL,
    artist_id integer NOT NULL,
    CONSTRAINT album_artist_pkey PRIMARY KEY (album_id, artist_id),
    CONSTRAINT album_artist_album_id_fkey FOREIGN KEY (album_id)
        REFERENCES album (id) ON DELETE CASCADE,
    CONSTRAINT album_artist_artist_id_fkey FOREIGN KEY (artist_id)
        REFERENCES artist (id) ON DELETE CASCADE
);
CREATE INDEX album_artist_artist_id_idx ON album_artist (artist_id);

CREATE TABLE artist_music (
    artist_id integer NOT NULL,
    music_id  integer NOT NULL,
    CONSTRAINT artist_music_pkey PRIMARY KEY (artist_id, music_id),
    CONSTRAINT artist_music_artist_id_fkey FOREIGN KEY (artist_id)
        REFERENCES artist (id) ON DELETE CASCADE,
    CONSTRAINT artist_music_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE
);
CREATE INDEX artist_music_music_id_idx ON artist_music (music_id);

-- =====================================================================
-- Interações do usuário com músicas
-- =====================================================================

CREATE TABLE music_user (
    music_id   integer     NOT NULL,
    user_id    integer     NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT music_user_pkey PRIMARY KEY (music_id, user_id),
    CONSTRAINT music_user_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE,
    CONSTRAINT music_user_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE
);
CREATE INDEX music_user_user_id_idx ON music_user (user_id);

CREATE TABLE rating (
    id         integer     GENERATED BY DEFAULT AS IDENTITY,
    music_id   integer     NOT NULL,
    user_id    integer     NOT NULL,
    rating     smallint    NOT NULL,
    deleted_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT rating_pkey PRIMARY KEY (id),
    CONSTRAINT rating_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE,
    CONSTRAINT rating_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE,
    CONSTRAINT rating_rating_check CHECK (rating BETWEEN 1 AND 5)
);
-- Uma avaliação ativa por usuário e música.
CREATE UNIQUE INDEX rating_music_id_user_id_key ON rating (music_id, user_id) WHERE deleted_at IS NULL;
CREATE INDEX rating_user_id_idx ON rating (user_id);

CREATE TABLE comments (
    id          integer     GENERATED BY DEFAULT AS IDENTITY,
    music_id    integer     NOT NULL,
    user_id     integer     NOT NULL,
    comment     text        NOT NULL,
    "timestamp" integer,    -- segundos desde o início da música
    deleted_at  timestamptz,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT comments_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE,
    CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE,
    CONSTRAINT comments_timestamp_check CHECK ("timestamp" >= 0)
);
CREATE INDEX comments_music_id_idx ON comments (music_id);
CREATE INDEX comments_user_id_idx ON comments (user_id);

-- Relação 1:0..1 com musics (music_id único).
CREATE TABLE music_stats (
    id       integer          GENERATED BY DEFAULT AS IDENTITY,
    music_id integer          NOT NULL,
    genre    varchar(100),
    duration integer,
    streams  integer          NOT NULL DEFAULT 0,
    rating   double precision,
    CONSTRAINT music_stats_pkey PRIMARY KEY (id),
    CONSTRAINT music_stats_music_id_key UNIQUE (music_id),
    CONSTRAINT music_stats_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE,
    CONSTRAINT music_stats_streams_check CHECK (streams >= 0)
);

-- =====================================================================
-- Playlists
-- =====================================================================

CREATE TABLE playlists (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(150) NOT NULL,
    is_private boolean      NOT NULL DEFAULT false,
    color      char(7),     -- hex: #RRGGBB
    deleted_at timestamptz,
    updated_at timestamptz  NOT NULL DEFAULT now(),
    created_at timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT playlists_pkey PRIMARY KEY (id),
    CONSTRAINT playlists_color_check CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE playlist_user (
    playlist_id integer NOT NULL,
    user_id     integer NOT NULL,
    is_admin    boolean NOT NULL DEFAULT false,
    CONSTRAINT playlist_user_pkey PRIMARY KEY (playlist_id, user_id),
    CONSTRAINT playlist_user_playlist_id_fkey FOREIGN KEY (playlist_id)
        REFERENCES playlists (id) ON DELETE CASCADE,
    CONSTRAINT playlist_user_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES "user" (id) ON DELETE CASCADE
);
CREATE INDEX playlist_user_user_id_idx ON playlist_user (user_id);

CREATE TABLE music_playlist (
    music_id    integer NOT NULL,
    playlist_id integer NOT NULL,
    CONSTRAINT music_playlist_pkey PRIMARY KEY (music_id, playlist_id),
    CONSTRAINT music_playlist_music_id_fkey FOREIGN KEY (music_id)
        REFERENCES musics (id) ON DELETE CASCADE,
    CONSTRAINT music_playlist_playlist_id_fkey FOREIGN KEY (playlist_id)
        REFERENCES playlists (id) ON DELETE CASCADE
);
CREATE INDEX music_playlist_playlist_id_idx ON music_playlist (playlist_id);

-- =====================================================================
-- Triggers de updated_at
-- =====================================================================

DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'plan_type', 'plan', 'user', 'system_data',
        'musics', 'lyrics', 'genre', 'album', 'artist',
        'rating', 'comments', 'playlists'
    ] LOOP
        EXECUTE format(
            'CREATE TRIGGER %I BEFORE UPDATE ON %I
             FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
            t || '_set_updated_at', t
        );
    END LOOP;
END;
$$;

-- =====================================================================
-- Dados iniciais
-- =====================================================================

INSERT INTO system_data DEFAULT VALUES;
